### PR TITLE
Suggested changes to repository and build

### PR DESCRIPTION
**Pull request by gep13**
I have just been going through the audit that was completed by the Cake.AddinDiscoverer tool, the output of which can be found here:

https://github.com/cake-contrib/Home/blob/master/Audit.xlsx

And I noticed a couple things that I thought could be updated. The main things were:

Pinning to Cake.Recipe 1.0.0
Updating the NuGet Metadata to include all recommended information
Please let me know if you have any questions about any of the changes in this PR.

### CODE REVIEW

**Comment by gep13** [comment]
@michalkowal please let me know if you have any questions about any of the changes in this PR.

**Review by michalkowal — APPROVED** [review]

**Comment by gep13** [comment]
@michalkowal thank you for taking the time to review and merge this PR, I really appreciate it!

Have we spoken about the possibility to moving this repository under the Cake-Contrib Organisation?  Is that something that you would be interested in?

**Comment by michalkowal** [comment]
Hi @gep13 

We haven't. I'm interested, but not right now - in the near future, I will try to handle this topic.
Thanks for your contribution.

**Comment by gep13** [comment]
@michalkowal that is great news that you are interested in moving it into the Organisation.  Just to let you know, in terms of effort for you, moving the repository into the Organisation shouldn't take more than a couple of minutes.  The remainder of the work in doing the setup is done by someone on the Cake Team, and the process is documented here:

https://github.com/cake-contrib/Home#how-do-i-as-an-addin-author-transfer-a-repository-to-the-organisation

Please feel free to reach out when you get to a point where you want to look at this.

**Pull request merged**
